# Generated by Django 5.0.6 on 2024-08-19 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_type", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("mileage", models.IntegerField()),
                ("zipcode", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("engine_modifications", models.TextField(blank=True, null=True)),
                ("transmission_modifications", models.TextField(blank=True, null=True)),
                ("body_modifications", models.TextField(blank=True, null=True)),
                ("brake_modifications", models.TextField(blank=True, null=True)),
                ("suspension_modifications", models.TextField(blank=True, null=True)),
                ("rims_tires", models.TextField(blank=True, null=True)),
                (
                    "mechanic_builder",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="vehicle_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="vehicle_profiles.vehicleprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="vehicle_profiles.vehicleprofile",
                    ),
                ),
            ],
        ),
    ]
