# Generated by Django 5.0.6 on 2024-07-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_listing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="zipcode",
            field=models.CharField(default="00000", max_length=10),
        ),
    ]
