# Generated by Django 5.0.6 on 2024-07-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_listing", "0002_car_zipcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="seller",
            new_name="owner",
        ),
    ]
