# Generated by Django 5.0.6 on 2024-07-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_listing", "0007_car_category_alter_car_make_alter_car_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="vin",
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="zipcode",
            field=models.CharField(default="28540", max_length=10),
        ),
    ]
