# Generated by Django 5.0.6 on 2024-07-23 16:53

import car_listing.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_listing", "0009_alter_car_vin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="vin",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                unique=True,
                validators=[car_listing.validators.validate_vin],
            ),
        ),
    ]
