# Generated by Django 5.0.6 on 2024-08-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_listing", "0014_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="mileage",
            field=models.PositiveIntegerField(max_length=7, null=True),
        ),
    ]
