# Generated by Django 5.0.6 on 2024-08-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_listing", "0016_alter_car_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="mileage",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
