# Generated by Django 5.0.6 on 2024-08-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_listing", "0021_alter_car_year_alter_car_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name="car",
            name="zipcode",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
