# Generated by Django 5.0.6 on 2024-08-06 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_listing", "0022_alter_car_year_alter_car_zipcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="category",
        ),
    ]
