# Generated by Django 5.0.6 on 2024-08-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_listing", "0024_alter_car_latitude_alter_car_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="make",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=100),
        ),
    ]
