# Generated by Django 5.0.6 on 2024-07-30 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_listing", "0013_carmake_alter_car_make_carmodel_alter_car_model"),
        ("messaging", "0002_alter_conversation_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="car",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="car_listing.car",
            ),
        ),
    ]
