# Generated by Django 5.0.6 on 2024-07-30 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_listing", "0013_carmake_alter_car_make_carmodel_alter_car_model"),
        ("messaging", "0003_message_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="car",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="car_listing.car",
            ),
        ),
    ]
