# Generated by Django 5.0.6 on 2024-08-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0007_remove_conversation_car_remove_message_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
