# Generated by Django 5.0.6 on 2024-08-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0009_chatsession_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
