# Generated by Django 5.0.6 on 2024-07-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="seller_type",
            field=models.CharField(
                blank=True,
                choices=[("private", "Private Seller"), ("dealer", "Dealer")],
                max_length=10,
                null=True,
            ),
        ),
    ]
