# Generated by Django 5.0.6 on 2024-07-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_profile_image_alter_profile_seller_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
